CREATE TABLE IF NOT EXISTS messages (
    id SERIAL PRIMARY KEY,
    task_id UUID UNIQUE NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE IF NOT EXISTS notifications (
    id SERIAL PRIMARY KEY,
    message TEXT NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
